### ISSUE TITLE
能发一下数据库结构吗

### ISSUE THREAD

**Issue by stuhk** [cliclitv/go-clicli#5]
能发一下数据库结构吗

**Comment by 132yse** [comment]
我们急需后端人员，如果加入我们，可以给你数据库权限

**Comment by stuhk** [comment]
> 我们急需后端人员，如果加入我们，可以给你数据库权限

要怎么加入

**Comment by 132yse** [comment]
> 要怎么加入
欢迎加入CliCli进击的巨人，群聊号码：561285033

**Comment by stuhk** [comment]
> > 要怎么加入
> > 欢迎加入CliCli进击的巨人，群聊号码：561285033

加了(*￣︶￣)

**Comment by jwchan1996** [comment]
🤔


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by jwchan1996** [comment]
@132yse 🤔


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by stuhk** [comment]
> @132yse 🤔
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

大佬好🤔

**Comment by 132yse** [comment]
我发了，关
