### ISSUE TITLE
管理权限漏洞

### ISSUE THREAD

**Issue by xww2652008969** [cliclitv/go-clicli#6]
![TIM截图20190602230208](https://user-images.githubusercontent.com/22444360/58763204-78317900-858a-11e9-9a2a-c6d614482b19.png)
由于设个人置界面出现设置用户权限然后消失 然后又看见post json 可以构造admin 
所以容易被获取管理权限

**Comment by 132yse** [comment]
收到收到~有时间改√

**Comment by 132yse** [comment]
搞定，关掉
